name : Validate the Pull Request

on :
    pull_request:
        branches: [ devolopment, deplotest ]
        types:
            - opened
            - synchronize
            - reopened
        paths:
            - 'force-app/**'
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: validate on Developerorg
              uses: jawills/sf-deploy@v1.0
              with:
                SFDX_AUTH_URL: ${{secrets.SFDX_AUTH_URL}}
                DRY_RUN: true
                  
