# Unique name for this workflow
name: Quick Deploy using Job ID

# Definition when the workflow should run
on:

  push:
    branches: [ devolopment ]

jobs:
  initial-setup:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get job ID file
        run: |
            git pull origin
            value=$(cat job_id.txt)
            echo The result is $value

      - name: Deploy
        shell: bash
        run: |
             echo "Deploying with job ID: $value"
             
      - name: 'Check aartifact'
        run: echo Checkout source code




      - name: 'Download job ID artifact'
        uses: actions/download-artifact@v4
      - name: Get job ID file
        run: |
            git pull
            value=$(cat job_id.txt)
            echo The result is $value
      - name: Deploy
        shell: bash
        run: |
            echo "Deploying with job ID: $value"



  #     - name: 'Install Salesforce CLI'
  #       run: |
  #           wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
  #           mkdir ~/sfdx
  #           tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
  #           echo "$HOME/sfdx/bin" >> $GITHUB_PATH
  #           ~/sfdx/bin/sfdx version

  #     - name: 'Installing java'
  #       run: |
  #         sudo apt-get update
  #         sudo apt install default-jdk

  #     - name: 'Populate auth file with SFDX_URL secret of integration org'
  #       shell: bash
  #       run: |
  #            echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt
  #       # Authenticate to org using the URL stored in the text file
  #     - name: 'Authenticate to Integration Org'
  #       run: |
  #            sfdx auth:sfdxurl:store -f ./SFDX_INTEGRATION_URL.txt -s -a integration
  #            echo NEW DEPLYMENT ID ${{ needs.validate-deployment-on-develop-org.outputs.SFDX_JobID }}
  #            echo APEX TESTS ${{env.APEX_TESTS}}

  # quick-deploy:
  #   runs-on: ubuntu-latest
  #   needs: initial-setup
  #   if: needs.validate-deployment-on-develop-org.outputs.SFDX_JobID != ''
  #   steps:
  #     - name: 'Quick Deploy'
  #       run: |
  #         sfdx force:source:quickdeploy -i ${{ needs.validate-deployment-on-develop-org.outputs.SFDX_JobID }} --verbose

